/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeneratePortraitRouteImport } from './routes/api/generate-portrait'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedStoryRouteImport } from './routes/_authenticated/story'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScenariosRouteImport } from './routes/_authenticated/scenarios'
import { Route as AuthenticatedMemoriesRouteImport } from './routes/_authenticated/memories'
import { Route as AuthenticatedKeepsakesRouteImport } from './routes/_authenticated/keepsakes'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCharacterRouteImport } from './routes/_authenticated/character'
import { Route as AuthenticatedBondsRouteImport } from './routes/_authenticated/bonds'
import { Route as AuthenticatedScenarioSessionIdRouteImport } from './routes/_authenticated/scenario.$sessionId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePortraitRoute = ApiGeneratePortraitRouteImport.update({
  id: '/api/generate-portrait',
  path: '/api/generate-portrait',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoryRoute = AuthenticatedStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScenariosRoute = AuthenticatedScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoriesRoute = AuthenticatedMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeepsakesRoute = AuthenticatedKeepsakesRouteImport.update({
  id: '/keepsakes',
  path: '/keepsakes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCharacterRoute = AuthenticatedCharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBondsRoute = AuthenticatedBondsRouteImport.update({
  id: '/bonds',
  path: '/bonds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScenarioSessionIdRoute =
  AuthenticatedScenarioSessionIdRouteImport.update({
    id: '/scenario/$sessionId',
    path: '/scenario/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bonds': typeof AuthenticatedBondsRoute
  '/character': typeof AuthenticatedCharacterRoute
  '/chat': typeof AuthenticatedChatRoute
  '/create': typeof AuthenticatedCreateRoute
  '/home': typeof AuthenticatedHomeRoute
  '/keepsakes': typeof AuthenticatedKeepsakesRoute
  '/memories': typeof AuthenticatedMemoriesRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/story': typeof AuthenticatedStoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/scenario/$sessionId': typeof AuthenticatedScenarioSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bonds': typeof AuthenticatedBondsRoute
  '/character': typeof AuthenticatedCharacterRoute
  '/chat': typeof AuthenticatedChatRoute
  '/create': typeof AuthenticatedCreateRoute
  '/home': typeof AuthenticatedHomeRoute
  '/keepsakes': typeof AuthenticatedKeepsakesRoute
  '/memories': typeof AuthenticatedMemoriesRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/story': typeof AuthenticatedStoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/scenario/$sessionId': typeof AuthenticatedScenarioSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bonds': typeof AuthenticatedBondsRoute
  '/_authenticated/character': typeof AuthenticatedCharacterRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/keepsakes': typeof AuthenticatedKeepsakesRoute
  '/_authenticated/memories': typeof AuthenticatedMemoriesRoute
  '/_authenticated/scenarios': typeof AuthenticatedScenariosRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/story': typeof AuthenticatedStoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/_authenticated/scenario/$sessionId': typeof AuthenticatedScenarioSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bonds'
    | '/character'
    | '/chat'
    | '/create'
    | '/home'
    | '/keepsakes'
    | '/memories'
    | '/scenarios'
    | '/settings'
    | '/story'
    | '/api/chat'
    | '/api/generate-portrait'
    | '/scenario/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bonds'
    | '/character'
    | '/chat'
    | '/create'
    | '/home'
    | '/keepsakes'
    | '/memories'
    | '/scenarios'
    | '/settings'
    | '/story'
    | '/api/chat'
    | '/api/generate-portrait'
    | '/scenario/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bonds'
    | '/_authenticated/character'
    | '/_authenticated/chat'
    | '/_authenticated/create'
    | '/_authenticated/home'
    | '/_authenticated/keepsakes'
    | '/_authenticated/memories'
    | '/_authenticated/scenarios'
    | '/_authenticated/settings'
    | '/_authenticated/story'
    | '/api/chat'
    | '/api/generate-portrait'
    | '/_authenticated/scenario/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGeneratePortraitRoute: typeof ApiGeneratePortraitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-portrait': {
      id: '/api/generate-portrait'
      path: '/api/generate-portrait'
      fullPath: '/api/generate-portrait'
      preLoaderRoute: typeof ApiGeneratePortraitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/story': {
      id: '/_authenticated/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof AuthenticatedStoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios': {
      id: '/_authenticated/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof AuthenticatedScenariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memories': {
      id: '/_authenticated/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AuthenticatedMemoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keepsakes': {
      id: '/_authenticated/keepsakes'
      path: '/keepsakes'
      fullPath: '/keepsakes'
      preLoaderRoute: typeof AuthenticatedKeepsakesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/character': {
      id: '/_authenticated/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof AuthenticatedCharacterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bonds': {
      id: '/_authenticated/bonds'
      path: '/bonds'
      fullPath: '/bonds'
      preLoaderRoute: typeof AuthenticatedBondsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenario/$sessionId': {
      id: '/_authenticated/scenario/$sessionId'
      path: '/scenario/$sessionId'
      fullPath: '/scenario/$sessionId'
      preLoaderRoute: typeof AuthenticatedScenarioSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBondsRoute: typeof AuthenticatedBondsRoute
  AuthenticatedCharacterRoute: typeof AuthenticatedCharacterRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedKeepsakesRoute: typeof AuthenticatedKeepsakesRoute
  AuthenticatedMemoriesRoute: typeof AuthenticatedMemoriesRoute
  AuthenticatedScenariosRoute: typeof AuthenticatedScenariosRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStoryRoute: typeof AuthenticatedStoryRoute
  AuthenticatedScenarioSessionIdRoute: typeof AuthenticatedScenarioSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBondsRoute: AuthenticatedBondsRoute,
  AuthenticatedCharacterRoute: AuthenticatedCharacterRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedKeepsakesRoute: AuthenticatedKeepsakesRoute,
  AuthenticatedMemoriesRoute: AuthenticatedMemoriesRoute,
  AuthenticatedScenariosRoute: AuthenticatedScenariosRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStoryRoute: AuthenticatedStoryRoute,
  AuthenticatedScenarioSessionIdRoute: AuthenticatedScenarioSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGeneratePortraitRoute: ApiGeneratePortraitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
